### ISSUE TITLE
did not work now

### ISSUE THREAD

**Issue by leftthomas** [Litreily/capturer#2]

**Comment by Litreily** [comment]
@leftthomas could you give more description?

**Comment by leftthomas** [comment]
@Litreily I have tested LOFTER,  but it can not download any images

**Comment by Litreily** [comment]
please pull again, it should be OK now

**Comment by leftthomas** [comment]
@Litreily , it works now, thank you.

**Comment by Litreily** [comment]
Add one more patch, commit [6340114](https://github.com/Litreily/capturer/commit/63401140885fcd60c3589487b3ae9d626774c270)
