### ISSUE TITLE
微博爬图bug

### ISSUE THREAD

**Issue by ciring** [Litreily/capturer#3]
不知道是什么原因，只有少部分图，是否因为碰到livephoto，我把79行删除后基本正常

**Comment by chenruisilalala** [comment]
不知道是什么原因，只有少部分图，是否因为碰到livephoto，我把79行删除后基本正常

**Comment by Litreily** [comment]
方便告知uid吗？79行是`break`用于退出程序，与图片多少应该并无关系。

**Comment by chenruisilalala** [comment]
> 方便告知uid吗？79行是`break`用于退出程序，与图片多少应该并无关系。

6697930990,第74张图后停止

**Comment by Litreily** [comment]
@chenruisilalala 微博爬虫已有更新，请pull后尝试是否仍旧存在问题
