### ISSUE TITLE
空间爬图报错

### ISSUE THREAD

**Issue by shenghaishxt** [Litreily/capturer#4]
2019-05-18 22:20:35,247 [INFO] User 78247843 login...
2019-05-18 22:21:14,020 [INFO] Getting g_tk...
2019-05-18 22:21:14,031 [INFO] Getting Cookies...
2019-05-18 22:21:16,300 [INFO] Getting ablum list id...

line 123, in _get_ablum_list for item in data['data']['albumListModeSort']:
KeyError: 'albumListModeSort'

希望您能看看是什么原因？

**Comment by Litreily** [comment]
每次都能重现吗？ 从错误信息来看是返回的数据中不包含"albumListModeSort"，需要进一步确认。如果可以重现，请在123行前加一行
`logging.info(data)`
之后提供log，谢谢

**Comment by xixia123** [comment]
你好，请问下为什么空间的相册里面的照片只能下载下来几张，其他的不能下载下来

**Comment by KeplerStr** [comment]
你好，我在运行过程中出现了安全验证 然后报错如下

DevTools listening on ws://127.0.0.1:7600/devtools/browser/98b330bc-b280-4cd1-8183-922e67e70249
2020-03-28 11:00:45,828 [INFO] User 641972386 login...
2020-03-28 11:00:50,292 [INFO] Getting g_tk...
2020-03-28 11:00:50,316 [ERROR] Getting g_tk failed, please check your QQ number and password

**Comment by cnyy7** [comment]
> 2019-05-18 22:20:35,247 [INFO] User 78247843 login...
> 2019-05-18 22:21:14,020 [INFO] Getting g_tk...
> 2019-05-18 22:21:14,031 [INFO] Getting Cookies...
> 2019-05-18 22:21:16,300 [INFO] Getting ablum list id...
> 
> line 123, in _get_ablum_list for item in data['data']['albumListModeSort']:
> KeyError: 'albumListModeSort'
> 
> 希望您能看看是什么原因？

```
        for item in data['data']['albumListModeSort']:
            album_list[item['name']] = item['id']
```
改为
```
        for item in data['data']['albumListModeClass']:
            for it in item['albumList']:
                album_list[it['name']] = it['id']
```
我这试着没问题
